### ISSUE TITLE
Port WAIL to Linux

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#2]
The question remains: where is the most appropriate location that is system independent where WAIL could reside on a Linux system? C:\WAIL is used for Windows, /Applications/WAIL on MacOS X.

**Comment by machawk1** [comment]
Per http://docs.python-guide.org/en/latest/shipping/freezing/

On Linux, an alternative to freezing is to create a Linux distro package[1] (e.g. .deb files for Debian or Ubuntu, or .rpm files for Red Hat and SuSE.)

[1] http://docs.python-guide.org/en/latest/shipping/packaging/#packaging-for-linux-distributions-ref

**Comment by kanihal** [comment]
/opt/wail should do it.

**Comment by machawk1** [comment]
@kanihal Thanks for the suggestion, `/opt/` is likely the most appropriate location.

Regarding your question, we did a revamp of [WAIL in Electron](https://github.com/n0tan3rd/wail) that is available for macOS, Windows, and Linux. It uses a different UI model (collection-based) and contains some different tools (e.g., it interfaces with Headless Chrome for crawling) but might fit your need. Please give it a try, as I do not currently have an estimate for the release of the Linux version of WAIL (this repo).

**Comment by kanihal** [comment]
@machawk1 WAIL in electron works on ubuntu & is easy to use. Nice work guys.

**Comment by machawk1** [comment]
There are a couple of outstanding issues that need to be resolved that are preventing the generation of a build for Linux. In using Ubuntu 18.10, `pip install wxPython` produces an error:

<details>
...
</details>

Another issue that the MAKEFILE.sh script is currently tailored to macOS with regard to installation directories.

**Comment by machawk1** [comment]
After manually installing wxPython from source (using the package's `python build.py dox --nodoc sip build`, installing Pyinstaller via (and needing to manually reference the binary's path due to pip not doing this by default), ...

**Comment by machawk1** [comment]
A more fundamental example that should probably be resolved first:
**wxTest.py**
```py
import wx

print('hello')
```
then
`~/.local/bin/pyinstaller wxTest.py --onefo;e --clean`
then
`./dist/wxTest`
produces
...

**Comment by machawk1** [comment]
https://groups.google.com/forum/#!searchin/wxpython-users/pip$20ubuntu%7Csort:date/wxpython-users/HeI3SK2kXws/489LCruzCwAJ may be a lead in resolving the shared library objects warning.

**Comment by machawk1** [comment]
Per https://wxpython.org/pages/downloads/, `pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.10 wxPython` should work on _my_ setup but the wxPython installation process is dependent on which flavor of Linux it is being built. This will need to be included in the Linux-specific MAKEFILE or thoroughly documented.

**Comment by machawk1** [comment]
After building wxPython , building WAIL, and running the binary, a shared object issue still arises at the time of binary execution.
```
$ ./dist/WAIL 
User likely has the binary in the wrong location.
Traceback (most recent call last):
  File "bundledApps/WAIL.py", line 48, in <module>
    import wx.adv
  File "/tmp/pip-build-Pw9LOp/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "wx/adv.py", line 13, in <module>
  File "/tmp/pip-build-Pw9LOp/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 684, in load_module
ImportError: libSDL-1.2.so.0: cannot open shared object file: No such file or directory
[3241] Failed to execute script WAIL
```

**Comment by machawk1** [comment]
`sudo apt install libsdl2-2.0` installs some form of the library but pyinstaller seems to want libsdl-1.2, which is obsolete. I may need to circle back install wxPython for my current system instead of relying on the 18.04 wheel.

Delegating the Linux build process to a Docker container is seeming pretty appealing at this point, given the necessary duct tape.

**Comment by machawk1** [comment]
Per https://github.com/wxWidgets/Phoenix/issues/991, `sudo apt install libsdl1.2debian` and `python bundledApps/WAIL.py`:

**Comment by machawk1** [comment]
@ibnesayeed We talked about this in-person but I figured I would ask you in a ticket to document efforts. Is there a way (alignment aside #396) to make the Linux version (below 50822e6) using Docker "less ugly" by default?

Linux:
<img width="379" alt="Screen Shot 2019-03-26 at 4 30 15 PM" src="https://user-images.githubusercontent.com/2514780/55031299-b471b780-4fe4-11e9-8704-bc7ddf2186c6.png">
macOS:
<img width="512" alt="Screen Shot 2019-03-26 at 4 31 17 PM" src="https://user-images.githubusercontent.com/2514780/55031300-b471b780-4fe4-11e9-8d8d-7a153cd70a92.png">

**Comment by ibnesayeed** [comment]
I don't necessarily find it ugly. Every desktop environment has its unique style of representing certain UI components. Cross-platform UI libraries can be classified in two categories, those that use a unified look and field across platforms by introducing their own UI styles or providing sufficient customization options (such as Electron-based UIs that allow you to write application using HTML/CSS) and those that give a higher-level abstraction of widgets and components that are then mapped to platform's native UI style. Currently, WAIL-Python is using the latter, so such differences are obvious.

That said, if you can experiment with various Linux desktop environments and see if it looks better in one or the other, we can perhaps set the Docker image up with a specific distro and desktop to behave like that. Alternatively, we can use a theme for the desktop environment in question (e.g., https://www.gnome-look.org/p/1013741/ for Mac-like UI in GTK/GNOME) and see if that matches your taste better. Another possibility is to use HTML renderer (which I think is an option in wxWidget) to make it more consistent cross-platform, but it might need more changes in the app itself.

**Comment by ibnesayeed** [comment]
When running the `/wail/WAIL` (or `./WAIL` command from `/wail` directory), I see it crash as following:

```
root@CONATINERID:/wail# ./WAIL 
User likely has the binary in the wrong location.
MEMGATOR checking http://matkelly.com/wail
Checking access to Heritrix at https://0.0.0.0:8443
Checking access to Heritrix at https://0.0.0.0:8443
Service: Failed to access Heritrix service at https://0.0.0.0:8443
Service: Failed to access Heritrix service at https://0.0.0.0:8443
Wayback(): Failed to access Wayback service at http://0.0.0.0:8080/wayback/
Wayback(): Failed to access Wayback service at http://0.0.0.0:8080/wayback/
Wayback(): Failed to access Wayback service at http://0.0.0.0:8080/wayback/
Wayback(): Failed to access Wayback service at http://0.0.0.0:8080/wayback/
**
Pango:ERROR:../pango/pango-layout.c:3871:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
Aborted (core dumped)
root@[CONATINERID]:/wail# 
```

**Comment by ibnesayeed** [comment]
Perhaps related to https://stackoverflow.com/questions/3225183/pango-error-after-a-minute-of-running
