### ISSUE TITLE
Cannot get 2013.2.19 to work in Windows

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#270]
As reported by Ed Pinsent of University of London--

Downloaded http://matkelly.com/wail_old/release/WAIL%200.2013.2.19.zip, unzipped, moved packages to C:\WAIL

When I run wail.exe, I get the following errors. Tried on both Win10 and WIn7, both cases have same problem.

```
WARNING: It's currently not possible to run Heritrix in background
         on Windows. It was just started minimized in a new Window
         and will be shut down as soon as you log off.

28/09/2017 16:05:42.06 Starting heritrix
https://lorem:ipsum@localhost:8443/engine/job/1506611141
TypeError: 'undefined' is not an object (evaluating 'build.click')

  phantomjs://webpage.evaluate():4
  phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():5
Using ad-hoc HTTPS certificate with fingerprint...
SHA1:89:C0:2A:EC:D4:96:9B:AA:3D:73:B9:B6:D1:DE:52:93:F0:C5:07:BE
Verify in browser before accepting exception.
engine listening at port 8443
operator login set per command-line
NOTE: We recommend a longer, stronger password, especially if your web
interface will be internet-accessible.

[XAMPP]: Searching for JDK or JRE HOME with reg query ...
ERROR: The system was unable to find the specified registry key or value.
. [XAMPP]: Could not find 32 bit or 64 bit JDK
. [XAMPP]: Looking for 32 bit JDK on 64 bit machine
ERROR: The system was unable to find the specified registry key or value.
. [XAMPP]: Could not find 32 bit JDK
. [XAMPP]: Looking for 32 bit or 64 bit JRE
ERROR: The system was unable to find the specified registry key or value.
. [XAMPP]: Could not find 32 bit or 64 bit JRE
. [XAMPP]: Looking for 32 bit JRE on 64 bit machine

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment
    CurrentVersion    REG_SZ    1.8
    BrowserJavaVersion    REG_SZ    11.144.2

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment\1.8
    RuntimeLib    REG_SZ    C:\Program Files (x86)\Java\jre1.8.0_144\bin\client\jvm.dll
    JavaHome    REG_SZ    C:\Program Files (x86)\Java\jre1.8.0_144
    MicroVersion    REG_SZ    0

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment\1.8.0_144
    JavaHome    REG_SZ    C:\Program Files (x86)\Java\jre1.8.0_144
    MicroVersion    REG_SZ    0
    RuntimeLib    REG_SZ    C:\Program Files (x86)\Java\jre1.8.0_144\bin\client\jvm.dll

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment\1.8.0_144\MSI
    INSTALLDIR    REG_SZ    C:\Program Files (x86)\Java\jre1.8.0_144\
    JU    REG_SZ
    OEMUPDATE    REG_SZ
    FROMVERSION    REG_SZ    NA
    FROMVERSIONFULL    REG_SZ
    PRODUCTVERSION    REG_SZ    8.0.1440.1
    EULA    REG_SZ
    JAVAUPDATE    REG_SZ    1
    AUTOUPDATECHECK    REG_SZ    1
    AUTOUPDATEDELAY    REG_SZ
    FullVersion    REG_SZ    1.8.0_144-b01


[XAMPP]: Using JRE

[XAMPP]: Seems fine!
[XAMPP]: Set JRE_HOME : C:\Program Files (x86)\Java\jre1.8.0_144
[XAMPP]: Set CATALINA_HOME : C:\WAIL\tomcat

Could Not Find C:\WAIL\tomcat\logs\catalina.pid
https://lorem:ipsum@localhost:8443/engine/job/1506611141
Using CATALINA_BASE:   "C:\WAIL\tomcat"
Using CATALINA_HOME:   "C:\WAIL\tomcat"
Using CATALINA_TMPDIR: "C:\WAIL\tomcat\temp"
Using JRE_HOME:        "C:\Program Files (x86)\Java\jre1.8.0_144"
Using CLASSPATH:       "C:\WAIL\tomcat\bin\bootstrap.jar;C:\WAIL\tomcat\bin\tomcat-juli.jar"
TypeError: 'undefined' is not an object (evaluating 'launch.click')

  phantomjs://webpage.evaluate():4
  phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():5
Sep 28, 2017 4:05:48 PM org.apache.catalina.startup.Catalina stopServer
SEVERE: Catalina.stop:
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at org.apache.catalina.startup.Catalina.stopServer(Catalina.java:499)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.catalina.startup.Bootstrap.stopServer(Bootstrap.java:371)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:453)
```

**Comment by machawk1** [comment]
Pulled 51e2d11001fe1415d4959bbd8de2533677cfe0d7 fresh to Win10 C:\wail then ran `bundledApps\MAKEFILE.bat`, which finishes and creates an .exe. Upon launching the EXE, there is a noticeable delay then an alert pops up saying, "Failed to execute script WAIL" with a title "Fatal Error".

**Comment by Krytical13** [comment]
Downloaded 3d879cd from win-fixes.

Same "Failed to execute script WAIL" error on windows 10

**Comment by machawk1** [comment]
Thanks for the confirmation, @Krytical13 . I am working on getting this back to stable on Windows in the `win-fixes` branch: https://github.com/machawk1/wail/tree/win-fixes

We also have an Electron version of WAIL at https://github.com/n0tan3rd/wail which should work in Windows 10. Please feel free to give it a try.
