### ISSUE TITLE
"Yes" to Java download with no network connection causes WAIL to crash

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#367]
To replicate, start WAIL (either from source 4bb739f1d78f4adfeac35ad8622e3b5e8e98fcba or binary) without any network connection without Java installed. Selecting "Yes", when running from source, produces an exception:

```
$ python bundledApps/WAIL.py
Traceback (most recent call last):
  File "bundledApps/WAIL.py", line 1774, in <module>
    mainAppWindow = TabController()
  File "bundledApps/WAIL.py", line 92, in __init__
    self.basicConfig = WAILGUIFrame_Basic(self.Notebook)
  File "bundledApps/WAIL.py", line 255, in __init__
    self.ensureEnvironmentVariablesAreSet()
  File "bundledApps/WAIL.py", line 417, in ensureEnvironmentVariablesAreSet
    self.installJava()
  File "bundledApps/WAIL.py", line 420, in installJava
    resp = requests.get(config.osx_java7DMG)
  File "/Users/machawk1/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/machawk1/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/machawk1/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/machawk1/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/machawk1/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='matkelly.com', port=80): Max retries exceeded with url: /wail/support/jdk-7u79-macosx-x64.dmg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10723de90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```
...that should be "caught" and mitigated in this instance.

**Comment by machawk1** [comment]
For completeness, when running from Py3 (above defaulted to Py2):

```
$ python3 bundledApps/WAIL.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x106bb5e48>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='matkelly.com', port=80): Max retries exceeded with url: /wail/support/jdk-7u79-macosx-x64.dmg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106bb5e48>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bundledApps/WAIL.py", line 1774, in <module>
    mainAppWindow = TabController()
  File "bundledApps/WAIL.py", line 92, in __init__
    self.basicConfig = WAILGUIFrame_Basic(self.Notebook)
  File "bundledApps/WAIL.py", line 255, in __init__
    self.ensureEnvironmentVariablesAreSet()
  File "bundledApps/WAIL.py", line 417, in ensureEnvironmentVariablesAreSet
    self.installJava()
  File "bundledApps/WAIL.py", line 420, in installJava
    resp = requests.get(config.osx_java7DMG)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='matkelly.com', port=80): Max retries exceeded with url: /wail/support/jdk-7u79-macosx-x64.dmg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106bb5e48>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```
