### ISSUE TITLE
Errors in using latest release of WAIL for Windows

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#370]
Esteban P. reported via e-mail:
```
Having said that, I wasn't able to properly use your software so far. Here's the traceback:

Traceback (most recent call last):
  File "<string>", line 138, in archiveNow
  File "<string>", line 263, in startTomcat
  File "C:\Downloads\pyinstaller-2.0\WAIL\build\pyi.win32\WAIL\out00-PYZ.pyz\subprocess", line 679, in __init__
  File "C:\Downloads\pyinstaller-2.0\WAIL\build\pyi.win32\WAIL\out00-PYZ.pyz\subprocess", line 893, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified

So of course the first thing that caught my eye was that "C:\Downloads\..." file path since my WAIL isn't installed on the C drive, let alone the Downloads folder. I searched across the WAIL folder and realized that path is hardcoded in many files:
\warcproxy-bin\build\pyi.win32\warcproxy\out00-Analysis.toc
\warcproxy-bin\build\pyi.win32\warcproxy\out00-COLLECT.toc 
\warcproxy-bin\build\pyi.win32\warcproxy\out00-EXE.toc
\warcproxy-bin\build\pyi.win32\warcproxy\out00-PKG.toc
\warcproxy-bin\build\pyi.win32\warcproxy\out00-PYZ.toc
\warcproxy-bin\build\pyi.win32\warcproxy\warnwarcproxy.txt
\warcproxy-bin\warcproxy.spec

So my question is: is this a bug? It looks like one to me since ideally it should pop-up a messagebox or something with a more user-friendly explanation if something important is missing.
If it's not a bug I'd appreciate it if you could point me out in the right direction to have this fixed.
```

warcproxy is no longer in current master and the paths lead me to believe he is using the current version-old version of WAIL for Window v0.2013.2.19.

The plan, in lieu of getting the code completely polished for a release, is to push out a beta version that at least gets the Windows version a little more caught up.

**Comment by machawk1** [comment]
Fix in master but will need verification on next Windows release.
