### ISSUE TITLE
Unsupported locale on Linux

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#401]
```
Unhandled exception in thread started by <bound method WAILGUIFrame_Basic.fetchMementos of <__main__.WAILGUIFrame_Basic object at 0x7f7338e86b88>>
Traceback (most recent call last):
  File "bundledApps/WAIL.py", line 430, in fetchMementos
    self.setMementoCount(mCount, len(archHosts))
  File "bundledApps/WAIL.py", line 368, in setMementoCount
    locale.setlocale(locale.LC_ALL, localeToSet)
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by machawk1** [comment]
From in the container:
```
# locale -a
C
C.UTF-8
POSIX
```

**Comment by machawk1** [comment]
Something like https://github.com/oduwsdl/ipwb/blob/31d1db939f1110791ad1b069b07ccba5655f36ef/ipwb/util.py#L114-L123 might work here. We may just want to send the empty string and let it default to the OS (as a caveat that this approach has been problematic elsewhere).
