### ISSUE TITLE
JRE/JDK checks prevent use on Windows

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#5]
Please define either JAVA_HOME or JAVACMD or make sure java.exe is in PATH
https://lorem:ipsum@localhost:8443/engine/job/1363023499

[XAMPP]: Searching for JDK or JRE HOME with reg query ...
ERROR: The system was unable to find the specified registry key or value.
. [XAMPP]: Could not find 32 bit or 64 bit JDK
. [XAMPP]: Looking for 32 bit JDK on 64 bit machine
ERROR: The system was unable to find the specified registry key or value.
. [XAMPP]: Could not find 32 bit JDK
. [XAMPP]: Looking for 32 bit or 64 bit JRE
ERROR: The system was unable to find the specified registry key or value.
. [XAMPP]: Could not find 32 bit or 64 bit JRE
. [XAMPP]: Looking for 32 bit JRE on 64 bit machine

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment
    Java7FamilyVersion    REG_SZ    1.7.0_15
    CurrentVersion    REG_SZ    1.7
    BrowserJavaVersion    REG_SZ    10.15.2

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment\1.7
    JavaHome    REG_SZ    C:\Program Files (x86)\Java\jre7
    RuntimeLib    REG_SZ    C:\Program Files (x86)\Java\jre7\bin\client\jvm.dll
    MicroVersion    REG_SZ    0

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment\1.7.0_
15
    JavaHome    REG_SZ    C:\Program Files (x86)\Java\jre7
    MicroVersion    REG_SZ    0
    RuntimeLib    REG_SZ    C:\Program Files (x86)\Java\jre7\bin\client\jvm.dll

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\JavaSoft\Java Runtime Environment\1.7.0_
15\MSI
    JU    REG_SZ    1
    OEMUPDATE    REG_SZ
    MODE    REG_SZ    C
    JQS    REG_SZ
    FROMVERSION    REG_SZ
    FROMVERSIONFULL    REG_SZ
    PRODUCTVERSION    REG_SZ    7.0.150
    INSTALLDIR    REG_SZ    C:\Program Files (x86)\Java\jre7\
    PATCHDIR    REG_SZ
    WEB_JAVA_SECURITY_LEVEL    REG_SZ
    WEB_JAVA    REG_SZ
    EULA    REG_SZ    0
    IEXPLORER    REG_SZ    1
    MOZILLA    REG_SZ    1
    JAVAUPDATE    REG_SZ    1
    AUTOUPDATECHECK    REG_SZ    1
    AUTOUPDATEDELAY    REG_SZ
    ImageCkSum    REG_SZ    799880791
    FullVersion    REG_SZ    1.7.0_15-b03

[XAMPP]: Using JRE

[XAMPP]: Seems fine!
[XAMPP]: Set JRE_HOME : C:\Program Files (x86)\Java\jre7
[XAMPP]: Set CATALINA_HOME : C:\WAIL\tomcat

Could Not Find C:\WAIL\tomcat\logs\catalina.pid
Using CATALINA_BASE:   "C:\WAIL\tomcat"
Using CATALINA_HOME:   "C:\WAIL\tomcat"
Using CATALINA_TMPDIR: "C:\WAIL\tomcat\temp"
Using JRE_HOME:        "C:\Program Files (x86)\Java\jre7"
Using CLASSPATH:       "C:\WAIL\tomcat\bin\bootstrap.jar;C:\WAIL\tomcat\bin\tomc
at-juli.jar"
https://lorem:ipsum@localhost:8443/engine/job/1363023499
TypeError: 'undefined' is not an object (evaluating 'build.click')

  phantomjs://webpage.evaluate():4
  phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():5
Mar 11, 2013 10:38:25 AM org.apache.catalina.startup.Catalina stopServer
SEVERE: Catalina.stop:
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at org.apache.catalina.startup.Catalina.stopServer(Catalina.java:499)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.catalina.startup.Bootstrap.stopServer(Bootstrap.java:371)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:453)

TypeError: 'undefined' is not an object (evaluating 'launch.click')

  phantomjs://webpage.evaluate():4
  phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():5

**Comment by machawk1** [comment]
The initial Java errors are replicable on a fresh Windows 10, WAIL version 0.2013.2.19.

![virtualbox_win10_07_09_2017_17_24_24](https://user-images.githubusercontent.com/2514780/30185963-9cfa9e6a-93f1-11e7-8f63-227f0b164e41.png)
