### ISSUE TITLE
docker build command stops after asking for the country of origin for the keyboard

### ISSUE THREAD

**Issue by JJJHolscher** [machawk1/wail#564]
On my arch linux machine, after running
```sh
git clone https://github.com/machawk1/wail.git
cd wail
docker build -t machawk1/wail .
```

Docker outputs _a bunch_, but then asks for `Country of origin for the keyboard: ` after enumerating 99 countries.
When I put in the number, country name, nothing or do not even press enter, the program never continues doing anything, it also doesn't quit.

I would like it to finish building instead.

**Comment by machawk1** [comment]
Thanks for the report, @JJJHolscher. I will see if I can replicate it and report back here.

**Comment by machawk1** [comment]
I first trip running the docker build command on my own macOS 13.4.1 machine and received a error just in the build process. This might not be the same issue. I will continue to dig.

```sh
...
 => ERROR [ 4/10] RUN        pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubunt  6.4s 
------                                                                                                              
 > [ 4/10] RUN        pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython==4.2.0        &&  pip3 install pyinstaller==5.3:                                                                 
#7 0.661 Looking in links: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04                     
#7 1.403 Collecting wxPython==4.2.0                                                                                 
#7 1.476   Downloading wxPython-4.2.0.tar.gz (71.0 MB)
#7 6.043     ERROR: Command errored out with exit status 1:
#7 6.043      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nl5yi0_e/wxPython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nl5yi0_e/wxPython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-nl5yi0_e/wxPython/pip-egg-info
#7 6.043          cwd: /tmp/pip-install-nl5yi0_e/wxPython/
#7 6.043     Complete output (7 lines):
#7 6.043     Traceback (most recent call last):
#7 6.043       File "<string>", line 1, in <module>
#7 6.043       File "/tmp/pip-install-nl5yi0_e/wxPython/setup.py", line 27, in <module>
#7 6.043         from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
#7 6.043       File "/tmp/pip-install-nl5yi0_e/wxPython/buildtools/config.py", line 30, in <module>
#7 6.043         from attrdict import AttrDict
#7 6.043     ModuleNotFoundError: No module named 'attrdict'
#7 6.043     ----------------------------------------
#7 6.297 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
------
executor failed running [/bin/sh -c pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython==4.2.0        &&  pip3 install pyinstaller==5.3]: exit code: 1
```

**Comment by machawk1** [comment]
https://askubuntu.com/questions/876240/how-to-automate-setting-up-of-keyboard-configuration-package appears to be a relevant way to remedy this issue if we are first able to replicate it.

**Comment by machawk1** [comment]
@JJJHolscher I am working on securing an Arch Linux OS, but the addition of the environment variable in branch `issue-564` might overcome the issue you are facing. If you get the chance, please run:

```bash
git clone https://github.com/machawk1/wail.git
cd wail
git checkout issue-564
docker build -t machawk1/wail .
```

...and let me know if you experience the same issue.

**Comment by JJJHolscher** [comment]
`docker build -t machawk1/wail .` ran successfully after running that code.
I wasn't able to verify the `./WAIL` command at the end since I already have Heritrix running and do not want to pause it in the foreseeable future.
