### ISSUE TITLE
DMG fails to build

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#580]
As reported by Dhanashree, in building the DMG using the MAKEFILE:

```
biplist.InvalidPlistException: module 'plistlib' has no attribute 'Data'

It seems the `biplist` library is attempting to access an attribute `Data` in `plistlib`, which has been removed in Python 3.11. I believe this is causing the `InvalidPlistException` error, as `biplist` is trying to read a plist file but is not compatible with the new version of Python.

To address this issue, I am considering the following potential fixes:
1. Update biplist: I will check if there is an updated version of the biplist  library that resolves this compatibility issue with Python 3.11.
2. Modify the code to use plistlib directly: Since recent versions of  plistlib support both binary and XML plist files, I could replace `biplist` with `plistlib` in the affected part of the code.
```

I verified that the issue persists in Python 3.12.0, macOS 14.6.1, Apple M1, current main branch HEAD [041be9b](https://github.com/machawk1/wail/commit/041be9b1cbb4e1d61c0d4acbbfabf7a7be77fd20).

**Comment by dhanashreedeshmukh** [comment]
The plistlib.Data compatibility issue with Python 3.11 has been resolved! I replaced plistlib.Data with bytes in biplist, and it now works smoothly.

**Comment by machawk1** [comment]
@dhanashreedeshmukh Can you submit a PR to this repo with this fix in place? I can then merge it in and we can close this issue. Thanks!

**Comment by dhanashreedeshmukh** [comment]
I have made the change directly to the biplist library in Python
environment (outside of a Git repository)

**Comment by machawk1** [comment]
```sh
machawk1@Macmini wail % sh bundledApps/MAKEFILE.sh                              
Would you like to install binary (i), create dmg (d), or both (b)? (i/d/b) d
Running makeWAIL()
Installing build requirements
Requirement already satisfied: attrdict3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.0.2)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from attrdict3) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: wxPython in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (4.2.2)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from wxPython) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: attrdict in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: biplist in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (1.0.3)
Requirement already satisfied: black in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (24.4.0)
Requirement already satisfied: charset_normalizer<3.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (2.1.1)
Requirement already satisfied: dmgbuild in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (1.6.1)
Requirement already satisfied: ds-store in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (1.3.1)
Requirement already satisfied: mac-alias in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (2.2.2)
Requirement already satisfied: pathlib2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (2.3.7.post1)
Requirement already satisfied: pyinstaller>=5.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (6.6.0)
Requirement already satisfied: pypubsub in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 10)) (4.0.3)
Requirement already satisfied: pystache in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 11)) (0.6.5)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 12)) (2.31.0)
Requirement already satisfied: schedule in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 13)) (1.2.1)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 14)) (1.16.0)
Requirement already satisfied: wheel in /Users/machawk1/Library/Python/3.12/lib/python/site-packages (from -r requirements.txt (line 15)) (0.44.0)
Requirement already satisfied: wxPython>=4.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 16)) (4.2.2)
Requirement already satisfied: click>=8.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from black->-r requirements.txt (line 3)) (8.1.7)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from black->-r requirements.txt (line 3)) (1.0.0)
Requirement already satisfied: packaging>=22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from black->-r requirements.txt (line 3)) (23.0)
Requirement already satisfied: pathspec>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from black->-r requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: platformdirs>=2 in /Users/machawk1/Library/Python/3.12/lib/python/site-packages (from black->-r requirements.txt (line 3)) (4.2.0)
Requirement already satisfied: setuptools>=42.0.0 in /Users/machawk1/Library/Python/3.12/lib/python/site-packages (from pyinstaller>=5.0->-r requirements.txt (line 9)) (75.2.0)
Requirement already satisfied: altgraph in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pyinstaller>=5.0->-r requirements.txt (line 9)) (0.17.4)
Requirement already satisfied: pyinstaller-hooks-contrib>=2024.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pyinstaller>=5.0->-r requirements.txt (line 9)) (2024.4)
Requirement already satisfied: macholib>=1.8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pyinstaller>=5.0->-r requirements.txt (line 9)) (1.16.3)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->-r requirements.txt (line 12)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->-r requirements.txt (line 12)) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->-r requirements.txt (line 12)) (2023.7.22)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Decompressing JDK 17 modules file for Heritrix
Archive:  ./modules.zip
  inflating: modules                 
/tmp/wail
Creating binary
/Library/Frameworks/Python.framework/Versions/3.12/bin/pyinstaller
/Library/Frameworks/Python.framework/Versions/3.12/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
🌌 Building universal binary
132 INFO: PyInstaller: 6.6.0, contrib hooks: 2024.4
132 INFO: Python: 3.12.0
139 INFO: Platform: macOS-15.3.1-arm64-arm-64bit
139 INFO: wrote /private/tmp/wail/WAIL.spec
142 INFO: Removing temporary files and cleaning cache in /Users/machawk1/Library/Application Support/pyinstaller
170 INFO: Extending PYTHONPATH with paths
['/private/tmp/wail', '/private/tmp/wail/bundledApps']
252 INFO: checking Analysis
252 INFO: Building Analysis because Analysis-00.toc is non existent
252 INFO: Running Analysis Analysis-00.toc
252 INFO: Target bytecode optimization level: 0
252 INFO: Initializing module dependency graph...
253 INFO: Caching module graph hooks...
263 INFO: Analyzing base_library.zip ...
813 INFO: Loading module hook 'hook-encodings.py' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/hooks'...
1561 INFO: Loading module hook 'hook-pickle.py' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/hooks'...
2057 INFO: Loading module hook 'hook-heapq.py' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/hooks'...
2251 INFO: Caching module dependency graph...
2295 INFO: Looking for Python shared library...
2297 INFO: Using Python shared library: /Library/Frameworks/Python.framework/Versions/3.12/Python
2297 INFO: Analyzing /private/tmp/wail/bundledApps/WAIL.py
2400 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
3093 INFO: Loading module hook 'hook-charset_normalizer.py' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
3262 INFO: Loading module hook 'hook-certifi.py' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
/private/tmp/wail/bundledApps/WAILConfig.py:34: SyntaxWarning: invalid escape sequence '\w'
  WAIL_VERSION = version_parser.GetFileVersion('C:\wail\WAIL.exe')
3424 INFO: Loading module hook 'hook-platform.py' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/hooks'...
3440 INFO: Loading module hook 'hook-xml.py' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/hooks'...
3441 INFO: Processing pre-safe import module hook win32com from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
3446 INFO: Loading module hook 'hook-pubsub.core.py' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
3589 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/hooks'...
3591 INFO: Processing module hooks...
3615 INFO: Performing binary vs. data reclassification (19 entries)
3618 INFO: Looking for ctypes DLLs
3621 INFO: Analyzing run-time hooks ...
3622 INFO: Including run-time hook '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
3626 INFO: Looking for dynamic libraries
3758 INFO: Warnings written to /private/tmp/wail/build/WAIL/warn-WAIL.txt
3768 INFO: Graph cross-reference written to /private/tmp/wail/build/WAIL/xref-WAIL.html
3832 INFO: checking PYZ
3832 INFO: Building PYZ because PYZ-00.toc is non existent
3832 INFO: Building PYZ (ZlibArchive) /private/tmp/wail/build/WAIL/PYZ-00.pyz
4085 INFO: Building PYZ (ZlibArchive) /private/tmp/wail/build/WAIL/PYZ-00.pyz completed successfully.
4087 INFO: EXE target arch: universal2
4087 INFO: Code signing identity: None
4089 INFO: checking PKG
4089 INFO: Building PKG because PKG-00.toc is non existent
4089 INFO: Building PKG (CArchive) WAIL.pkg
18345 INFO: Building PKG (CArchive) WAIL.pkg completed successfully.
18347 INFO: Bootloader /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
18347 INFO: checking EXE
18347 INFO: Building EXE because EXE-00.toc is non existent
18347 INFO: Building EXE from EXE-00.toc
18347 INFO: Copying bootloader EXE to /private/tmp/wail/dist/WAIL
18347 INFO: Converting EXE to target arch (universal2)
18349 INFO: Removing signature(s) from EXE
18363 INFO: Appending PKG archive to EXE
18389 INFO: Fixing EXE headers for code signing
18396 INFO: Re-signing the EXE
18458 INFO: Building EXE from EXE-00.toc completed successfully.
18459 INFO: checking BUNDLE
18459 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
18459 INFO: Building BUNDLE BUNDLE-00.toc
18497 INFO: Signing the BUNDLE...
18557 INFO: Building BUNDLE BUNDLE-00.toc completed successfully.
Deleting binary
Optimizing for Mac
> Removing MemGator (Linux)
> Removing MemGator (Window)
> Removing Java (Windows)
> Removing MemGator (pre-Apple Silicon)
Moving WAIL.app to /Applications
Cleaning up byproducts, deleting ./dist and ./build/WAIL
Building Disk Image
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/biplist/__init__.py", line 126, in readPlist
    result = reader.parse()
             ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/biplist/__init__.py", line 234, in parse
    return self.readRoot()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/biplist/__init__.py", line 248, in readRoot
    raise NotBinaryPlistException()
biplist.NotBinaryPlistException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/biplist/__init__.py", line 141, in readPlist
    result = wrapDataObject(result, for_binary=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/biplist/__init__.py", line 154, in wrapDataObject
    elif isinstance(o, (bytes, plistlib.Data)) and for_binary:
                               ^^^^^^^^^^^^^
AttributeError: module 'plistlib' has no attribute 'Data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/dmgbuild", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/__main__.py", line 48, in main
    build_dmg(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/core.py", line 243, in build_dmg
    load_settings(settings_file, options)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/core.py", line 73, in load_settings
    exec(compile(fp.read(), filename, "exec"), settings, settings)
  File "./build/dmgbuild_settings.py", line 27, in <module>
    badge_icon = icon_from_app(application)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./build/dmgbuild_settings.py", line 12, in icon_from_app
    plist = biplist.readPlist(plist_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/biplist/__init__.py", line 143, in readPlist
    raise InvalidPlistException(e)
biplist.InvalidPlistException: module 'plistlib' has no attribute 'Data'
Deleting binary
Tweaking OS file associations
2025-03-03 13:41:36.110 defaults[53026:2945496] 
Domain /Applications/WAIL.app/Contents/Info.plist does not exist
failed to scan /Applications/WAIL.app: -43
```

**Comment by machawk1** [comment]
A solution might be to just hard-code the string. It is a filename we control. I am not certain about the need for the overhead of reading the value from the Info.plist file other than for cross-platformedness, which is currently a non-issue.

**Comment by machawk1** [comment]
Closed in a32538bdd1b9d09e59510a8568ffa2a565da944d
